In [2]:
import numpy as np
students = np.random.randint(50,101,size=(50,5))
students

array([[ 69,  85,  96,  54,  87],
       [ 86,  90,  88,  63,  99],
       [ 55,  91, 100,  94,  61],
       [ 50,  97,  68,  89,  94],
       [ 54,  70,  75,  93,  90],
       [ 73,  60,  82,  59,  72],
       [ 56,  50,  64,  66,  74],
       [ 93,  71,  57,  61,  71],
       [ 79,  50,  99,  74,  68],
       [ 94,  75,  61,  75,  55],
       [ 90,  86,  65,  89,  62],
       [ 98,  83,  65,  82,  94],
       [ 98,  71,  87,  74,  55],
       [ 79,  89,  96,  91,  84],
       [ 64,  61,  93,  53,  62],
       [ 65,  90,  92,  91,  90],
       [ 98,  96,  93,  80,  90],
       [ 62,  56,  88,  59,  78],
       [ 65,  93,  78,  71,  57],
       [ 62,  69,  59,  82,  88],
       [ 64,  96,  84,  84,  50],
       [ 51,  91,  86,  85,  60],
       [ 88,  96,  96,  75,  98],
       [ 70,  61,  89,  84,  58],
       [ 53,  69,  95,  75,  65],
       [ 98,  90,  87,  80,  64],
       [ 53,  88,  90,  87,  90],
       [ 77,  83,  87,  80,  70],
       [ 68,  51,  76,  55,  51],
       [ 55,  

In [3]:
students[0,0]
students[:1,:]
students[:1] #前一個學生
students[:2] #前2個學生
students[-5:] #最後5個學生

array([[77, 88, 71, 56, 81],
       [93, 92, 73, 51, 78],
       [61, 60, 61, 73, 99],
       [67, 74, 87, 98, 71],
       [75, 79, 95, 75, 65]])

In [4]:
students[:,0] #第一科所有分數
students[:,-1] #最後一科所有分數

array([87, 99, 61, 94, 90, 72, 74, 71, 68, 55, 62, 94, 55, 84, 62, 90, 90,
       78, 57, 88, 50, 60, 98, 58, 65, 64, 90, 70, 51, 54, 78, 95, 68, 75,
       98, 58, 94, 70, 95, 65, 53, 86, 80, 52, 53, 81, 78, 99, 71, 65])

In [5]:
np.sum(students[:1]) #第一個學生總分
np.sum(students[:2],axis=1) #前2個學生的總分 
np.sum(students,axis=1) #全班每位學生的總分
np.mean(students,axis=0) #每一科全班的平均
np.median(students,axis=0) #每一科全班的中位數

array([68.5, 81. , 86. , 75. , 71.5])